In [1]:
import tensorflow as tf
from twenty_forty_eight_linux import TwentyFortyEight
from collections import deque
import numpy as np

In [2]:
INPUT_DIM = 1
HIDDEN_LAYER_UNITS = 5
OUTPUT_DIM = 2
learning_rate = 1e-4

In [3]:
# None helyett lehetne 1 is; mivel a bemenet függ a kimenettől
state = tf.placeholder(tf.float32, shape=[None, INPUT_DIM], name="state_tensor")
direction = tf.placeholder(tf.float32, shape=[None, OUTPUT_DIM])

In [4]:
weights = {"W1": tf.get_variable("W1", shape=(INPUT_DIM, HIDDEN_LAYER_UNITS),
                                 initializer=tf.contrib.layers.xavier_initializer()),
           "W2": tf.get_variable("W2", shape=(HIDDEN_LAYER_UNITS, OUTPUT_DIM),
                                 initializer=tf.contrib.layers.xavier_initializer())}

In [5]:
h1 = tf.matmul(state, weights["W1"])

In [6]:
activation_hidden = tf.nn.relu(h1)

In [7]:
output = tf.matmul(activation_hidden, weights["W2"])

In [8]:
output_softmax = tf.nn.softmax(output)

### Loss calc

In [9]:
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(output, direction))

In [10]:
#train_opt = tf.train.RMSPropOptimizer(learning_rate)

In [11]:
train_opt = tf.train.GradientDescentOptimizer(learning_rate)

In [12]:
train_grad = train_opt.compute_gradients(loss)

In [13]:
# varázslat a graddal

In [14]:
#train_apply_grad = train_opt.apply_gradients(# varázsolt grad)

In [15]:
train_apply_grad = train_opt.apply_gradients(train_grad)

## TEST purposes

In [16]:
inp_prev = np.random.rand(10000000)

In [17]:
step1 = np.round(inp_prev)
step2 = np.ones_like(step1) - step1
inp = inp_prev.reshape(10000000,1)
final_label = np.vstack((step2, step1)).T

In [18]:
inp[0], final_label[0]

(array([ 0.37538987]), array([ 1.,  0.]))

# Main

In [19]:
sess = tf.InteractiveSession()

In [20]:
sess.run(tf.global_variables_initializer())

In [27]:
init_w1 = sess.run(weights["W2"])

In [ ]:
aa = sess.run(train_grad, feed_dict={state: np.arange(16, dtype=np.float32).reshape(1, 16),
                                       direction: np.eye(4, dtype=np.float32)[3].reshape(1, 4)})

In [21]:
sess.run([train_apply_grad, loss], feed_dict={state: inp,
                                       direction: final_label})

[None, 0.67715365]

In [25]:
sess.run(output_softmax, feed_dict={state: np.array([0.0]).reshape(1, 1)})

array([[ 0.5,  0.5]], dtype=float32)

In [28]:
init_w1

array([[ 0.79504526, -0.76072639],
       [ 0.18157819, -0.41787955],
       [-0.8714146 ,  0.67155695],
       [ 0.317047  ,  0.30271745],
       [ 0.44693506, -0.51620954]], dtype=float32)

In [32]:
weights["W1"].eval()[1]

array([-0.06593533,  0.10715821, -0.15057448,  0.07183631, -0.27002403,
        0.24723899,  0.12091051,  0.22173989,  0.02316024, -0.2837238 ,
        0.18369323, -0.27287886,  0.16186078, -0.15225048, -0.04605703,
       -0.07088382, -0.03151333,  0.25089255,  0.12522036,  0.25528222,
        0.2377699 ,  0.19715932, -0.02274823,  0.16625535, -0.10987602,
       -0.02663509,  0.25376844,  0.02643684,  0.27958894,  0.16725305,
       -0.03994039,  0.04259572, -0.07249348, -0.26008213, -0.28938228,
       -0.0347009 ,  0.04967287,  0.11082995,  0.09472182,  0.00163631,
        0.22430104, -0.02458203, -0.20409006,  0.02319853,  0.07626298,
       -0.235374  , -0.11304885,  0.25646082, -0.05775839, -0.1338999 ], dtype=float32)

In [18]:
np.arange(16, dtype=np.float32).reshape(1, 16)

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.]], dtype=float32)

array([[ 0.,  1.,  0.,  0.]], dtype=float32)